/**
* Defines für den Laser-Ranger
*
* Hokuyo URG-04LX: fov 240°, 681 samples
*/

#ifndef LASER_H
#define LASER_H

#include <math.h>


#define LASER_FOV_DEG (240.0)


#define LASER_SAMPLES (681)


#define LASER_RANGE_MIN (0.35)


#define LASER_RANGE_MAX (4.0)


#define LASER_RANGE_EPSILON (0.001)


#define LASER_RANGEINDEX_FROM_ANGLE_DEG(degree) \
	((int)((degree/(LASER_FOV_DEG/2)) * LASER_SAMPLES/2 + LASER_SAMPLES/2))


#define LASER_DEGREE_FROM_RANGEINDEX(index) \
	((double)(index*LASER_ANGULAR_RESOLUTION_DEG+LASER_MIN_ANGLE_DEG))


#define LASER_FOV_RAD (LASER_FOV_DEG * M_PI / 180.0)


#define LASER_ANGULAR_RESOLUTION_DEG (LASER_FOV_DEG / LASER_SAMPLES)


#define LASER_ANGULAR_RESOLUTION_RAD (LASER_FOV_RAD / LASER_SAMPLES)


#define LASER_MAX_ANGLE_RAD (LASER_FOV_RAD/2.0)


#define LASER_MIN_ANGLE_RAD (-LASER_MAX_ANGLE_RAD)


#define LASER_MAX_ANGLE_DEG (LASER_FOV_DEG/2.0)


#define LASER_MIN_ANGLE_DEG (-LASER_MAX_ANGLE_DEG)

#endif
